namespace Kyloe.Diagnostics
{
    public enum DiagnosticKind
    {
        NeverClosedBlockCommentError,
        NeverClosedStringLiteralError,
        ExpectedTokenError,
        UnknownCharacterError,
        InvalidIntLiteralError,
        InvalidFloatLiteralError,
        ExpectedExpressionError,
        ExpectedValueError,
        UnsupportedBinaryOperation,
        UnsupportedUnaryOperation,
        MissmatchedTypeError,
        NonExistantNameError,
        ExpectedModifiableValueError,
        UnsupportedAssignmentOperation,
        ExpectedTypeNameError,
        MemberNotFoundError,
        MemberAccessError,
        MemberAccessNotAllowed,
        NotCallableError,
        NoMatchingFunctionError,
        CannotCallStaticMethodError,
        InstanceRequiredToCallError,
        NameAlreadyExistsError,
        FunctionWithSameParametersExistsError,
        RedefinedParameterError,
    }
}